// Back-end logic
function numberArray(userNumber) {
  // Array to store the numbers generated by for loop
  var numbers = [];
  for (var i = 1; i <= userNumber; i++) {
    // Condition "pingpong", "pong" and "ping"
    if ((i % 3 === 0) && (i % 5 === 0)) {

      numbers.push("pingpong")

    } else if (i % 5 === 0) {

      numbers.push("pong")

    } else if (i % 3 === 0) {

      numbers.push("ping")

    } else {

      numbers.push(i)

    }
  }
  return numbers;
}

// Front-end logic
$(document).ready(function() {
  $("form#ping-pong").submit(function(event) {
    event.preventDefault();

    // Clear the result field before displaying new result
    $("ul").empty();

    // Store user input as a number
    var userNumber = parseInt($("input#userNumber").val());
    // Test
    // console.log(userNumber);

    // Don't accept negative number
    if (userNumber < 0) {
      alert("This is not a positive number");
    }

    var result = numberArray(userNumber);
    // Test
    // console.log(result);

    for (var index = 0; index < result.length; index += 1) {
      $("ul#result").append("<li>" + result[index] + "</li>")
    }

  });
});
